use_frameworks!

platform :ios, '10.0'

#  远程使用要添加 source
source 'https://github.com/achaoac/MFRouterSpec.git'

target 'MFRouter_Example' do
#  本地调试
  pod 'MFRouter', :path => '../'
#  远程使用
#  pod 'MFRouter'

  target 'MFRouter_Tests' do
    inherit! :search_paths

    
  end
end
